### PR TITLE
automatically enable GPU on Colab

### PR DESCRIPTION
**Pull request by TomPham97**

### CODE REVIEW

**Comment by TomPham97** [comment]
The 2nd commit is based on nbdev2's git merge driver and [Jupyter save hook](https://nbdev.fast.ai/tutorials/git_friendly_jupyter.html) to optimize git in Jupyter notebook ([source](https://www.fast.ai/#the-jupytergit-problem)).

**Review by JoaoLages — COMMENTED** [review]
I'm not a big fan of `nbdev-merge` to be honest. I prefer Jupytext, although it does not save the Jupyter notebook's output.

Additionaly, it seems that `nbdev-merge` does not solve our problems with notebooks in GitHub:
image

From what I see, this PR adds this line (`!nvidia-smi -L # enable GPU on Colab`) at the beginning of each Colab notebook, is that right? If so, maybe it's better to close this PR and I add that line directly in the `main` branch. What do you think?

**Comment by TomPham97** [comment]
> I prefer Jupytext, although it does not save the Jupyter notebook's output.

Jupytext would indeed be necessary for further collaborations down the line!

> If so, maybe it's better to close this PR and I add that line directly in the main branch.

That would be great, thank you so much! ☺️

**Comment by JoaoLages** [comment]
> > I prefer Jupytext, although it does not save the Jupyter notebook's output.
> 
> Jupytext would indeed be necessary for further collaborations down the line!

Totally agree. If we see the need, let's go back to this!

image
I'm trying that command and still, it doesn't activate the GPU automatically. Perhaps there's a way to change the runtime type automatically.

**Pull request closed without merging**
